name: Publish Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (use actual version number)'
        required: true
        default: '<major>.<minor>.<patch>'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish release
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.email "${{ secrets.GITHUBUSER }}"
          git config --global user.name "CodeFreakBot"
          ./gradlew release -x check -x bootJar -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseVersion }}
